services:
  weatherlystics-db:
    container_name: weatherlystics_db
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .dockerenv

    networks:
      - weatherlystics
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    restart: always
    ports:
      - 5050:80
    env_file:
      - .dockerenv
    networks:
      - weatherlystics
networks:
  weatherlystics:
    name: weatherlystics
