name: Unit Test

on:
  push:

jobs:
  Jest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run Tests
        run: |
          cd ./weatherlystics_fe/
          npm install
          npm test